name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            whoami
            sudo -l
            which docker
            cd ~/repos/AberdeenRSS/FlightManagementClient
            git checkout main
            git pull
            sudo /usr/bin/docker build . -t flight-management-client:latest
            cd /usr/share/uoarocketry-docker/docker
            sudo /usr/bin/docker compose stop
            sudo /usr/bin/docker compose up -d
